import React from "react";
import ProjectCard from "./ProjectCard";
import { ProjectType } from "@/types/Project";
import Button from "./Button";

const projects: ProjectType[] = [
  {
    id: 1,
    title: "Roblox Store",
    description:
      "Full-stack roblox store platform with more than 175K Follower on Instagram. Build using secure payment integration, real-time inventory management, and advanced analytics dashboard.",
    imageUrl: "/rosstoreid.webp",
    projectUrl: "https://rosstoreid.com/",
    tags: ["Next.js", "PostgreSQL", "Xendit"],
  },
  {
    id: 2,
    title: "Halostemba",
    description:
      "Creating high school social media platform, twitter like. A menfess and counseling application made for the final task at SMK Negeri 7 Semarang.",
    imageUrl: "/halostemba.jpg",
    projectUrl: "https://www.instagram.com/halostemba/",
    tags: ["Nextjs", "Docker", "HeadlessUI"],
  },
  {
    id: 3,
    title: "Cek Kodam App",
    description:
      "This is a simple Next.js Project. The kodam's name was generated by making API request to OpenAI's GPT-3 API and Dall-e 3 API for generating the image. The project is inspired by a clip from Kobo Kanaeru that asking her friend's (Zeta) about her kodam's name.",
    imageUrl: "/cek-kodam-app.jpg",
    projectUrl: "https://github.com/AmdaaRaijen/Cek-Kodam-App",
    tags: ["NextJs", "Open-AI", "TailwindCSS"],
  },
];

export default function ProjectSection() {
  return (
    <section
      className="relative min-h-screen w-full overflow-hidden p-8 sm:p-20 mt-28 md:mt-0"
      id="projects"
    >
      {/* Glow Effects */}
      <div className="absolute right-1/4 top-1/3 w-[500px] h-[500px] bg-[radial-gradient(circle_at_center,rgba(135,77,177,0.3),transparent_70%)] blur-3xl animate-pulse" />
      <div className="absolute left-1/4 bottom-1/3 w-[400px] h-[400px] bg-[radial-gradient(circle_at_center,rgba(135,77,177,0.2),transparent_70%)] blur-3xl animate-pulse" />

      {/* Content */}
      <div className="relative z-10 max-w-7xl mx-auto space-y-12">
        {/* Header */}
        <div className="text-center space-y-4">
          <h2 className="text-5xl sm:text-6xl font-bold text-white">
            Featured <span className="text-purple">Projects</span>
          </h2>
          <p className="text-lg text-white/70 max-w-2xl mx-auto">
            A selection of my recent work in web development and security
            analysis
          </p>
        </div>

        {/* Projects Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {projects.map((project) => (
            <ProjectCard key={project.id} project={project} />
          ))}
        </div>

        {/* View All Button */}
        <div className="flex justify-center pt-8">
          <Button>View All Projects</Button>
        </div>
      </div>
    </section>
  );
}
